language: node_js
node_js:
- 8
- 7
- 6
matrix:
  include:
  - node_js: 6
    env: DEPLOY=true
after_success: if [[ $DEPLOY == "true" ]] ; then ./node_modules/.bin/gulp condensation:deploy
  ; else echo "no deploy" ; fi
env:
  global:
  - secure: DAhNi21r+qhWcl5gvj/eae41OsD/dbLY+m7iE0ZM9yMWaH/limHhUmXwrSr9sIgLgg8A2hke84dIfiDqI2ogeiuqf9AVqbeYKUoDRk9SUZDTF94VWLCNgc9n1Gv1+vAZzSzb1xTkcVnF+pXzSvcS4LxkbXEcqevrXQPZM3x3sSVz2Vi5wiZpKq2Tgqd3MM9SaaFl4rwNWODOTvJgG+0jLOSwXS8v+kLJ19wBSQH9wyao5ijbptA3SeuVj4fix9uxfJ9DaxFCLaULohmFFJ7YYIWlfGlHHs6khInU4b80+3+OiEd9diFk8mkhB4xYP+geKdvueWoWyF1/957eFUV3F3yG3iDD1VFHmBOZJkgoRfOYQqsHSZotT+PsNVAFz1G0p8/2aBZ8zNX7D+vrzRtvNn8GdB7i9ldoKItdkey0n/vPkRdzVQT57xmEwXgfyegKCV8B2wTJoxgOhioxlym0vmpR0IdBbfbpJUct3ORR1nc+BFCT7+RnEsJSFlJmODBz+3lOhEeOY8/A2jjD1pZ5+jyJecPJFWEwT3xNnKxvzfR6AbSWKpNFssVrC6m6ykxqZmpIrqPljh36Ytedbtk8p00DLJWrd122VHGsSfCHCdV5BufVXUe3LpyfSqDKVR6SOF/w8Ura4xEmsW/rUv+wa/zLgJV/c2YaSAvdE/ZuDSk=
  - secure: kFZZCZ05n3181C7Fx1U/9HyGgu5tfhgLByRVtriFblEkMesm9kuWkzGW+x8hek1oYiEJ9Uho4zNaKaWJXHfa2O8DcKaqWpmk0vy14IZiTs30XHjmK1q4tuqosH1YTbrDOBesUd2bUCIi+wXtWaXTEd0lXS4/rpu2aaeIFJLybavv1tIinOsjJ6EfeUuxhpWZqoJEX8aIsJwI2duyd0lFrjEti8Q4Ji24QyBROXwoZjf1YarL3gmkC8PTEzlsZcIYd6DawlV6Weed5oJSuBIre4V0P0oTPWvkYKxe/OOahKC6OT6yYA403Clj8mFwluALeTgCvYyA8mSKg2TJDXsogH72GHpdCgquCTx6wv68pPsxb76smJrTYz98dsxo/7dWNpkYLNj2Y6CXbsp+BnMFYRcCMSBst3VNs+jp/1OAEV+jNOaOWpONhY0n8VY/77MWdvZOxtORMOsMcuWLyr6Pj3YK5Gsj5PsZ6P/8jrN3MFQqfdrhGVLdY0I4QdZVPnASAAhXTROQFAAver4LAwPSztIADcbkW5u5jnHGtj5jqLi/02VVQX36BdM09YSphu6SikzJCvW+mSB+4Yxi3YBcbiEDQ1ksqv5QzdM9xcjVQ7N5zZjXwr+G70hN9MhMaXYV0x+yMHg0V1hV25a+6In/njk4nuV8bFquPT61xFT46no=
